name: Auto-publish
on:
  pull_request: {}
  push:
    paths: index.bs
    branches: [main]

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html"
          VALIDATE_LINKS: false
          BUILD_FAIL_ON: link-error
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_NOTIFICATIONS_CC: dom@w3.org
          W3C_BUILD_OVERRIDE: |
            TR: https://www.w3.org/TR/webrtc-encoded-transform/
            status: WD
